package org.rdf2salesforce.model;

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from odette.ttl
 * 
 * @author Auto-generated by schemagen on 16 Jun 2015 18:08
 */
public class Odette {
	/**
	 * <p>
	 * The RDF model that holds the vocabulary terms
	 * </p>
	 */
	private static Model m_model = ModelFactory.createDefaultModel();

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "https://vocab.eccenca.com/odette/#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	public static Model getM_model() {
		return m_model;
	}

	public static void setM_model(Model m_model) {
		Odette.m_model = m_model;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = getM_model().createResource(NS);

	public static final Property additionalLink = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#additionalLink");

	public static final Property address = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#address");

	/**
	 * <p>
	 * Repeatable in various languages, a maximum number of 5 lines per language
	 * is recommended.
	 * </p>
	 */
	public static final Property addressLineText = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#addressLineText");

	public static final Property billingAddress = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#billingAddress");

	/**
	 * <p>
	 * For B2B processes (in XML messages), this information may be transmitted
	 * with a language attribute and is repeatable. One line per language is
	 * recommended.
	 * </p>
	 */
	public static final Property city = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#city");

	public static final Property countryCode = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#countryCode");

	public static final Property directParent = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#directParent");

	public static final Property emailAddress = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#emailAddress");

	public static final Property faxNumber = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#faxNumber");

	public static final Property fiscalRegistrationId = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#fiscalRegistrationId");

	public static final Property generalContact = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#generalContact");

	public static final Property homepage = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#homepage");

	public static final Property isClientOf = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#isClientOf");

	public static final Property isSupplierOf = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#isSupplierOf");

	public static final Property lastUpdate = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#lastUpdate");

	public static final Property logo = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#logo");

	public static final Property mailingAddress = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#mailingAddress");

	/**
	 * <p>
	 * The attribute can be repeated in various languages. A maximum of 1 line
	 * per language is recommended. For B2B processes (in XML messages), this
	 * information may be transmitted with a language attribute and is
	 * repeatable. For creation or change of business entity data, this field is
	 * required.
	 * </p>
	 */
	public static final Property name = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#name");

	public static final Property officeLocation = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#officeLocation");

	public static final Property position = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#position");

	public static final Property postBoxId = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#postBoxId");

	public static final Property postCode = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#postCode");

	public static final Property postCodePoBox = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#postCodePoBox");

	/**
	 * <p>
	 * The attribute can be repeated in various languages. A maximum of 1 line
	 * per language is recommended. For B2B processes (in XML messages), this
	 * information may be transmitted with a language attribute and is
	 * repeatable.
	 * </p>
	 */
	public static final Property previousName = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#previousName");

	public static final Property standardFormContract = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#standardFormContract");

	/**
	 * <p>
	 * For B2B processes (in XML messages), this information may be transmitted
	 * with a language attribute and is repeatable. A maximum of 2 lines per
	 * language is recommended.
	 * </p>
	 */
	public static final Property street = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#street");

	public static final Property subCountryCode = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#subCountryCode");

	public static final Property telephoneNumber = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#telephoneNumber");

	public static final Property timeZone = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#timeZone");

	/**
	 * <p>
	 * The attribute can be repeated in various languages. A maximum of 1 line
	 * per language is recommended. For B2B processes (in XML messages), this
	 * information may be transmitted with a language attribute and is
	 * repeatable.
	 * </p>
	 */
	public static final Property tradeName = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#tradeName");

	public static final Property vATRegistrationId = getM_model()
			.createProperty("https://vocab.eccenca.com/odette/#vATRegistrationId");

	/**
	 * <p>
	 * Recommeded usage: Variant 1: Structured address Street, Post Code, City,
	 * Country Code Variant 2: Structured Address Post Box ID, Post Code POBox,
	 * City, Country Code For creation or change of business entity data, this
	 * field is required.
	 * </p>
	 */
	public static final Resource Address = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#Address");

	/**
	 * <p>
	 * When adding, changing, or deactivating a Business Entity, only one
	 * Business Entity shall be included in an administration message, in case
	 * of a response to a 'request information' message the Business Entity is
	 * repeatable to allow the transmission of all relevant sub-entities.
	 * </p>
	 */
	public static final Resource BusinessEntity = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#BusinessEntity");

	public static final Resource Country = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#Country");

	public static final Resource Document = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#Document");

	public static final Resource Feature = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#Feature");

	/**
	 * <p>
	 * equals to entity-type 001
	 * </p>
	 */
	public static final Resource LegalHeadOffice = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#LegalHeadOffice");

	/**
	 * <p>
	 * equals to entity-type 003
	 * </p>
	 */
	public static final Resource NonRegisteredEntity = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#NonRegisteredEntity");

	/**
	 * <p>
	 * equals to entity-type 002
	 * </p>
	 */
	public static final Resource OtherRegisteredEntity = getM_model()
			.createResource("https://vocab.eccenca.com/odette/#OtherRegisteredEntity");

}