package org.rdf2salesforce.model;

import com.hp.hpl.jena.rdf.model.*;

/**
 * Vocabulary definitions from odette.ttl
 * 
 * @author Auto-generated by schemagen on 16 Jun 2015 18:08
 */
public class Odette {
	/**
	 * <p>
	 * The RDF model that holds the vocabulary terms
	 * </p>
	 */
	private static Model m_model = ModelFactory.createDefaultModel();

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "https://vocab.eccenca.com/odette/#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final Property additionalLink = m_model
			.createProperty("https://vocab.eccenca.com/odette/#additionalLink");

	public static final Property address = m_model
			.createProperty("https://vocab.eccenca.com/odette/#address");

	/**
	 * <p>
	 * Repeatable in various languages, a maximum number of 5 lines per language
	 * is recommended.
	 * </p>
	 */
	public static final Property addressLineText = m_model
			.createProperty("https://vocab.eccenca.com/odette/#addressLineText");

	public static final Property billingAddress = m_model
			.createProperty("https://vocab.eccenca.com/odette/#billingAddress");

	/**
	 * <p>
	 * For B2B processes (in XML messages), this information may be transmitted
	 * with a language attribute and is repeatable. One line per language is
	 * recommended.
	 * </p>
	 */
	public static final Property city = m_model
			.createProperty("https://vocab.eccenca.com/odette/#city");

	public static final Property countryCode = m_model
			.createProperty("https://vocab.eccenca.com/odette/#countryCode");

	public static final Property directParent = m_model
			.createProperty("https://vocab.eccenca.com/odette/#directParent");

	public static final Property emailAddress = m_model
			.createProperty("https://vocab.eccenca.com/odette/#emailAddress");

	public static final Property faxNumber = m_model
			.createProperty("https://vocab.eccenca.com/odette/#faxNumber");

	public static final Property fiscalRegistrationId = m_model
			.createProperty("https://vocab.eccenca.com/odette/#fiscalRegistrationId");

	public static final Property generalContact = m_model
			.createProperty("https://vocab.eccenca.com/odette/#generalContact");

	public static final Property homepage = m_model
			.createProperty("https://vocab.eccenca.com/odette/#homepage");

	public static final Property isClientOf = m_model
			.createProperty("https://vocab.eccenca.com/odette/#isClientOf");

	public static final Property isSupplierOf = m_model
			.createProperty("https://vocab.eccenca.com/odette/#isSupplierOf");

	public static final Property lastUpdate = m_model
			.createProperty("https://vocab.eccenca.com/odette/#lastUpdate");

	public static final Property logo = m_model
			.createProperty("https://vocab.eccenca.com/odette/#logo");

	public static final Property mailingAddress = m_model
			.createProperty("https://vocab.eccenca.com/odette/#mailingAddress");

	/**
	 * <p>
	 * The attribute can be repeated in various languages. A maximum of 1 line
	 * per language is recommended. For B2B processes (in XML messages), this
	 * information may be transmitted with a language attribute and is
	 * repeatable. For creation or change of business entity data, this field is
	 * required.
	 * </p>
	 */
	public static final Property name = m_model
			.createProperty("https://vocab.eccenca.com/odette/#name");

	public static final Property officeLocation = m_model
			.createProperty("https://vocab.eccenca.com/odette/#officeLocation");

	public static final Property position = m_model
			.createProperty("https://vocab.eccenca.com/odette/#position");

	public static final Property postBoxId = m_model
			.createProperty("https://vocab.eccenca.com/odette/#postBoxId");

	public static final Property postCode = m_model
			.createProperty("https://vocab.eccenca.com/odette/#postCode");

	public static final Property postCodePoBox = m_model
			.createProperty("https://vocab.eccenca.com/odette/#postCodePoBox");

	/**
	 * <p>
	 * The attribute can be repeated in various languages. A maximum of 1 line
	 * per language is recommended. For B2B processes (in XML messages), this
	 * information may be transmitted with a language attribute and is
	 * repeatable.
	 * </p>
	 */
	public static final Property previousName = m_model
			.createProperty("https://vocab.eccenca.com/odette/#previousName");

	public static final Property standardFormContract = m_model
			.createProperty("https://vocab.eccenca.com/odette/#standardFormContract");

	/**
	 * <p>
	 * For B2B processes (in XML messages), this information may be transmitted
	 * with a language attribute and is repeatable. A maximum of 2 lines per
	 * language is recommended.
	 * </p>
	 */
	public static final Property street = m_model
			.createProperty("https://vocab.eccenca.com/odette/#street");

	public static final Property subCountryCode = m_model
			.createProperty("https://vocab.eccenca.com/odette/#subCountryCode");

	public static final Property telephoneNumber = m_model
			.createProperty("https://vocab.eccenca.com/odette/#telephoneNumber");

	public static final Property timeZone = m_model
			.createProperty("https://vocab.eccenca.com/odette/#timeZone");

	/**
	 * <p>
	 * The attribute can be repeated in various languages. A maximum of 1 line
	 * per language is recommended. For B2B processes (in XML messages), this
	 * information may be transmitted with a language attribute and is
	 * repeatable.
	 * </p>
	 */
	public static final Property tradeName = m_model
			.createProperty("https://vocab.eccenca.com/odette/#tradeName");

	public static final Property vATRegistrationId = m_model
			.createProperty("https://vocab.eccenca.com/odette/#vATRegistrationId");

	/**
	 * <p>
	 * Recommeded usage: Variant 1: Structured address Street, Post Code, City,
	 * Country Code Variant 2: Structured Address Post Box ID, Post Code POBox,
	 * City, Country Code For creation or change of business entity data, this
	 * field is required.
	 * </p>
	 */
	public static final Resource Address = m_model
			.createResource("https://vocab.eccenca.com/odette/#Address");

	/**
	 * <p>
	 * When adding, changing, or deactivating a Business Entity, only one
	 * Business Entity shall be included in an administration message, in case
	 * of a response to a 'request information' message the Business Entity is
	 * repeatable to allow the transmission of all relevant sub-entities.
	 * </p>
	 */
	public static final Resource BusinessEntity = m_model
			.createResource("https://vocab.eccenca.com/odette/#BusinessEntity");

	public static final Resource Country = m_model
			.createResource("https://vocab.eccenca.com/odette/#Country");

	public static final Resource Document = m_model
			.createResource("https://vocab.eccenca.com/odette/#Document");

	public static final Resource Feature = m_model
			.createResource("https://vocab.eccenca.com/odette/#Feature");

	/**
	 * <p>
	 * equals to entity-type 001
	 * </p>
	 */
	public static final Resource LegalHeadOffice = m_model
			.createResource("https://vocab.eccenca.com/odette/#LegalHeadOffice");

	/**
	 * <p>
	 * equals to entity-type 003
	 * </p>
	 */
	public static final Resource NonRegisteredEntity = m_model
			.createResource("https://vocab.eccenca.com/odette/#NonRegisteredEntity");

	/**
	 * <p>
	 * equals to entity-type 002
	 * </p>
	 */
	public static final Resource OtherRegisteredEntity = m_model
			.createResource("https://vocab.eccenca.com/odette/#OtherRegisteredEntity");

}